version: '3'

volumes:
  database:
    driver: local

services:
  db:
    platform: linux/amd64
    image: postgres:16.0-alpine3.18
    container_name: mr-ss_database-container
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgres
