version: '3'

volumes:
  database:
    driver: local

services:
  db:
    platform: linux/amd64
    image: postgres:16.0-alpine3.18
    restart: always
    container_name: mr-ss_database-container
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgres
